// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAchZsFP2u2cdaymc6sTGshQLEY-LkWjm0',
    appId: '1:155129196688:web:d837fb2022c77dccece815',
    messagingSenderId: '155129196688',
    projectId: 'authentication-2c6cb',
    authDomain: 'authentication-2c6cb.firebaseapp.com',
    storageBucket: 'authentication-2c6cb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5wLE1pn9_Rj9erWNf1cz8jmartgb3gsQ',
    appId: '1:155129196688:android:7c48a8211d7d2384ece815',
    messagingSenderId: '155129196688',
    projectId: 'authentication-2c6cb',
    storageBucket: 'authentication-2c6cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNYi-vPo7jfE3SgwwY87I1CiOEJswu1ok',
    appId: '1:155129196688:ios:be34ca4c6cb4c825ece815',
    messagingSenderId: '155129196688',
    projectId: 'authentication-2c6cb',
    storageBucket: 'authentication-2c6cb.appspot.com',
    iosBundleId: 'com.example.uiCampusNav',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNYi-vPo7jfE3SgwwY87I1CiOEJswu1ok',
    appId: '1:155129196688:ios:c2246f16fbce63b6ece815',
    messagingSenderId: '155129196688',
    projectId: 'authentication-2c6cb',
    storageBucket: 'authentication-2c6cb.appspot.com',
    iosBundleId: 'com.example.uiCampusNav.RunnerTests',
  );
}
